### ISSUE TITLE
Unable to install on Version 1.22.1 (1.22.1)

### ISSUE THREAD

**Issue by datatalking** [mkloubert/vscode-kanban#10]
I've installed and reloaded, added the following into my code base, different tries into my settings.

Why won't this just install like every other app?

Normally Microsoft products are not known for reliability but on my iMac, I'm impressed with how well it works but your extension is the first that won't just poof load.

Help.

`{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
			"kanban": {
				"openOnStartup": true
			}
		}
}`

**Comment by mkloubert** [comment]
@datatalking 

I cannot reproduce the issue ... I have created and opened a workspace folder file with exactly the same content, you have posted here, (on a Mac) with extension version 1.13.1 and latest VSCode (1.24.1).

You have to install VSCode 1.23 at least, because the extension makes use of new [WebView API](https://code.visualstudio.com/docs/extensions/webview).

**Comment by datatalking** [comment]
Hi Marcel… the visual studio is saying that 1.22.1 is the most recent and There are currently no updates available.

How do I download a specific version?

Thankyou for the rapid turnaround?

**Comment by datatalking** [comment]
Sorry, never mind i forgot that msft doesn’t make good code so i had to manually download the new program.

Installing now. thanks again!
