### ISSUE TITLE
[Suggestion] Filter by Category

### ISSUE THREAD

**Issue by samael205** [mkloubert/vscode-kanban#12]
Hi,

It would be a powerful tool to filter the cards by category or type. Or even by assigned user

**Comment by mkloubert** [comment]
@samael205 

**Filters can be used since version 1.16.0** (s. [Filter section](https://github.com/mkloubert/vscode-kanban#filter-) for more information).

![demo8](https://user-images.githubusercontent.com/4951215/42049529-952fa84a-7b06-11e8-9a8e-ee783eb771ae.gif)

Filters will be saved into a `vscode-kanban.filter` file inside `.vscode` subfolder of the underlying workspace.

[filtrex](https://github.com/joewalnes/filtrex#expressions) is used as engine here.

**Comment by samael205** [comment]
Thank you, there came a time when I had so many cards that it's crazy to look for scroll among so Man y 😂
