### ISSUE TITLE
Categories Remains Blank after time period

### ISSUE THREAD

**Issue by samael205** [mkloubert/vscode-kanban#4]
There is a time when the blackboard with the categories remains blank, without tasks. as if it were initialized.

This is normal?
I would not know how to reproduce it. I just know that I have to close the Kanban tab and reopen the command.

**Comment by mkloubert** [comment]
@samael205 

**No, this is a bug, which should be fixed since version 1.8.0.**

I also added a reload button, when this should happen again or you edit the `.vscode/vscode-kanban.json` file outside manually.

![screenshot1](https://user-images.githubusercontent.com/4951215/40840174-e3490fa6-65a5-11e8-9257-9f839574151e.png)
